Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public string Model { get; set; }
    public int MachineId { get; set; }
    public int MinEngineerCount { get; set; }

    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if(EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index", "Engineers");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Engineer engineer, int MachineId)
    {
      if(MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index", "Engineers");
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId= new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", "Engineers");
    }

    public ActionResult Delete(int id)
    {
        var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
        return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
        _db.Machines.Remove(thisMachine);
        _db.SaveChanges();
        return RedirectToAction("Index", "Engineers");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
        var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
        _db.EngineerMachine.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index", "Engineers");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1>Assign an Engineer to @Model.Model</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  @Html.Label("Select an engineer")
  @Html.DropDownList("EngineerId")
  <input type="submit" value="Add" class="btn btn-warning"/>
}

<button class="btn btn-dark">@Html.ActionLink("Go back", "Details", new { id = @Model.MachineId })</button>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1 class="text-center">Create Machine</h1>
<div class="row mt-5">
  <div class="col-6 offset-3">
    @using (Html.BeginForm())
    {
      @Html.LabelFor(model => model.Model)
      @Html.TextBoxFor(model => model.Model, new { @class="form-control", @required="required" })

      @Html.LabelFor(model => model.MinEngineerCount)
      @Html.TextBoxFor(model => model.MinEngineerCount, new { @type="number", @class="form-control mb-3", @required="required", @min="1" })
      

      @Html.Label("Select an engineer to start working: ")
      @Html.DropDownList("EngineerId")

      <input type="submit" value="Create" class="btn btn-success create-btn"/>
    }
  </div>
</div>

<button class="btn btn-dark create-btn">@Html.ActionLink("Back to home", "Index", "Engineers")</button>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete Machine: @Model.Model<h2>

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-danger" />
}

<button class="btn btn-dark">@Html.ActionLink("Go back", "Details", new { id = @Model.MachineId })</button>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1 class="text-center">Machine: @Model.Model</h1>
<h3>Minimum Engineers Needed: @Model.MinEngineerCount</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <h4>@Model.Model does not currently have any engineers assigned to it</h4>
}
else
{
  <h3>Machines:</h3>
  <ol>
    @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Engineer.Name</li>
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" class="btn btn-danger"/>
      }
    }
  </ol>
}

<div class="row">
  <div class="col-2 offset-2">
    <button class="btn btn-dark">@Html.ActionLink("Edit machine", "Edit", new { id = @Model.MachineId })</button>
  </div>
  <div class="col-2">
    <button class="btn btn-danger">@Html.ActionLink("Delete machine", "Delete", new { id = @Model.MachineId })</button>
  </div>
  <div class="col-2">
    <button class="btn btn-dark">@Html.ActionLink("Add engineer", "AddEngineer", new { id = @Model.MachineId })</button>
  </div>
  <div class="col-2">
      <button class="btn btn-dark">@Html.ActionLink("Back home", "Index", "Engineers")</button>
  </div>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1>Edit: @Model.Model</h1>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  @Html.LabelFor(model => model.Model)
  @Html.TextBoxFor(model => model.Model, new { @class="form-control" })

  @Html.LabelFor(model => model.MinEngineerCount)
  @Html.TextBoxFor(model => model.MinEngineerCount, new { @type="number", @min="1", @class="form-control"})

  @Html.Label("Select an engineer to start working:")
  @Html.DropDownList("EngineerId")
  <input type="submit" value="Edit" class="btn btn-warning"/>
}

<button class="btn btn-dark">@Html.ActionLink("Go back", "Details", new { id = @Model.MachineId })</button>